<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Áo Thun Local Brand Unisex Summer Fresh TS282',
                'slug' => 'ao-thun-local-brand-unisex-summer-fresh-ts282',
                'image' => 'ao-thun-sp1.webp',
                'price' => 199000,
                'sale_price' => NULL,
                'quantity' => 39,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Áo Thun Local Brand Unisex Seasonal Tshirt TS295',
                'slug' => 'ao-thun-local-brand-unisex-seasonal-tshirt-ts295',
                'image' => 'ao-thun-sp2.webp',
                'price' => 189000,
                'sale_price' => NULL,
                'quantity' => 33,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Áo Thun Local Brand Unisex Capybara With Reindeer Antlers Tshirt TS293',
                'slug' => 'ao-thun-local-brand-unisex-capybara-reindeer-antlers-tshirt-ts293',
                'image' => 'ao-thun-sp3.webp',
                'price' => 179000,
                'sale_price' => NULL,
                'quantity' => 31,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Áo Thun Local Brand Unisex Summer Fresh Tshirt TS282',
                'slug' => 'ao-thun-local-brand-unisex-summer-fresh-tshirt-ts282-2',
                'image' => 'ao-thun-sp4.webp',
                'price' => 169000,
                'sale_price' => NULL,
                'quantity' => 49,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Áo Thun Dài Tay Local Brand Unisex Academy LongSleeve Tshirt TS292',
                'slug' => 'ao-thun-dai-tay-local-brand-unisex-academy-longsleeve-tshirt-ts292',
                'image' => 'ao-thun-sp5.webp',
                'price' => 159000,
                'sale_price' => NULL,
                'quantity' => 69,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Áo Thun Local Brand Unisex Dino Petite Tshirt TS287',
                'slug' => 'ao-thun-local-brand-unisex-dino-petite-tshirt-ts287',
                'image' => 'ao-thun-sp6.webp',
                'price' => 149000,
                'sale_price' => NULL,
                'quantity' => 30,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Áo Thun Local Brand Unisex Carita Feliz Flower Tshirt TS279',
                'slug' => 'ao-thun-local-brand-unisex-carita-feliz-flower-tshirt-ts279',
                'image' => 'ao-thun-sp7.webp',
                'price' => 139000,
                'sale_price' => NULL,
                'quantity' => 39,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Áo Polo Local Brand Unisex Sporty Stripes Royal Club AP061',
                'slug' => 'ao-polo-local-brand-unisex-sporty-stripes-royal-club-ap061',
                'image' => 'ao-polo-sp1.webp',
                'price' => 129000,
                'sale_price' => NULL,
                'quantity' => 29,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Áo Polo Local Brand Unisex Tyrannosaurus Polo Shirt AP060',
                'slug' => 'ao-polo-local-brand-unisex-tyrannosaurus-polo-shirt-ap060',
                'image' => 'ao-polo-sp2.webp',
                'price' => 119000,
                'sale_price' => NULL,
                'quantity' => 49,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Áo Polo Local Brand Unisex Flame AP055',
                'slug' => 'ao-polo-local-brand-unisex-flame-ap055',
                'image' => 'ao-polo-sp3.webp',
                'price' => 129000,
                'sale_price' => NULL,
                'quantity' => 19,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Áo Polo Local Brand Unisex Graphic Hanoi Famous AP031',
                'slug' => 'ao-polo-local-brand-unisex-graphic-hanoi-famous-ap031',
                'image' => 'ao-polo-sp4.webp',
                'price' => 139000,
                'sale_price' => NULL,
                'quantity' => 59,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Áo Polo Local Brand Unisex Kitten Embroidered AP022',
                'slug' => 'ao-polo-local-brand-unisex-kitten-embroidered-ap022',
                'image' => 'ao-polo-sp5.webp',
                'price' => 149000,
                'sale_price' => NULL,
                'quantity' => 89,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Áo Polo Local Brand Unisex Special Collection Premium AP018',
                'slug' => 'ao-polo-local-brand-unisex-special-collection-premium-ap018',
                'image' => 'ao-polo-sp6.webp',
                'price' => 159000,
                'sale_price' => NULL,
                'quantity' => 19,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Áo Polo Local Brand Unisex Simpled Logo AP016',
                'slug' => 'ao-polo-local-brand-unisex-simpled-logo-ap016',
                'image' => 'ao-polo-sp7.webp',
                'price' => 169000,
                'sale_price' => NULL,
                'quantity' => 49,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Áo Sơ Mi Local Brand Unisex Classic Oxford ASM001',
                'slug' => 'ao-so-mi-local-brand-unisex-classic-oxford-asm001',
                'image' => 'ao-somi-sp1.webp',
                'price' => 179000,
                'sale_price' => NULL,
                'quantity' => 25,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Áo Sơ Mi Local Brand Unisex Vintage Cuban Collar ASM002',
                'slug' => 'ao-so-mi-local-brand-unisex-vintage-cuban-collar-asm002',
                'image' => 'ao-somi-sp2.webp',
                'price' => 189000,
                'sale_price' => NULL,
                'quantity' => 30,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Áo Sơ Mi Local Brand Unisex Summer Breeze ASM003',
                'slug' => 'ao-so-mi-local-brand-unisex-summer-breeze-asm003',
                'image' => 'ao-somi-sp3.webp',
                'price' => 199000,
                'sale_price' => NULL,
                'quantity' => 20,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Áo Sơ Mi Local Brand Unisex Floral Pattern ASM004',
                'slug' => 'ao-so-mi-local-brand-unisex-floral-pattern-asm004',
                'image' => 'ao-somi-sp4.webp',
                'price' => 209000,
                'sale_price' => NULL,
                'quantity' => 35,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Áo Sơ Mi Local Brand Unisex Striped ASM005',
                'slug' => 'ao-so-mi-local-brand-unisex-striped-asm005',
                'image' => 'ao-somi-sp5.webp',
                'price' => 219000,
                'sale_price' => NULL,
                'quantity' => 28,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Quần Jeans Local Brand Unisex Slim Fit QJ001',
                'slug' => 'quan-jeans-local-brand-unisex-slim-fit-qj001',
                'image' => 'quan-sp1.webp',
                'price' => 299000,
                'sale_price' => NULL,
                'quantity' => 50,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Quần Jeans Local Brand Unisex Ripped QJ002',
                'slug' => 'quan-jeans-local-brand-unisex-ripped-qj002',
                'image' => 'quan-sp2.webp',
                'price' => 309000,
                'sale_price' => NULL,
                'quantity' => 40,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Quần Tây Local Brand Unisex Classic QT001',
                'slug' => 'quan-tay-local-brand-unisex-classic-qt001',
                'image' => 'quan-sp3.webp',
                'price' => 289000,
                'sale_price' => NULL,
                'quantity' => 35,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Quần Tây Local Brand Unisex Modern Fit QT002',
                'slug' => 'quan-tay-local-brand-unisex-modern-fit-qt002',
                'image' => 'quan-sp4.webp',
                'price' => 279000,
                'sale_price' => NULL,
                'quantity' => 30,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Quần Shorts Local Brand Unisex Cargo QS001',
                'slug' => 'quan-shorts-local-brand-unisex-cargo-qs001',
                'image' => 'quan-sp5.webp',
                'price' => 199000,
                'sale_price' => NULL,
                'quantity' => 45,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Quần Shorts Local Brand Unisex Chino QS002',
                'slug' => 'quan-shorts-local-brand-unisex-chino-qs002',
                'image' => 'quan-sp6.webp',
                'price' => 189000,
                'sale_price' => NULL,
                'quantity' => 42,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Nón Local Brand Unisex Baseball Cap NL001',
                'slug' => 'non-local-brand-unisex-baseball-cap-nl001',
                'image' => 'pk-sp1.webp',
                'price' => 99000,
                'sale_price' => NULL,
                'quantity' => 60,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Nón Local Brand Unisex Bucket Hat NL002',
                'slug' => 'non-local-brand-unisex-bucket-hat-nl002',
                'image' => 'pk-sp2.webp',
                'price' => 89000,
                'sale_price' => NULL,
                'quantity' => 55,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Nón Local Brand Unisex Beanie NL003',
                'slug' => 'non-local-brand-unisex-beanie-nl003',
                'image' => 'pk-sp3.webp',
                'price' => 79000,
                'sale_price' => NULL,
                'quantity' => 50,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Dây Nịt Local Brand Unisex Leather Belt DN001',
                'slug' => 'day-nit-local-brand-unisex-leather-belt-dn001',
                'image' => 'pk-sp4.webp',
                'price' => 159000,
                'sale_price' => NULL,
                'quantity' => 40,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Dây Nịt Local Brand Unisex Canvas Belt DN002',
                'slug' => 'day-nit-local-brand-unisex-canvas-belt-dn002',
                'image' => 'pk-sp5.webp',
                'price' => 139000,
                'sale_price' => NULL,
                'quantity' => 38,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Túi Local Brand Unisex Crossbody Bag TL001',
                'slug' => 'tui-local-brand-unisex-crossbody-bag-tl001',
                'image' => 'pk-sp6.webp',
                'price' => 259000,
                'sale_price' => NULL,
                'quantity' => 35,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Túi Local Brand Unisex Backpack TL002',
                'slug' => 'tui-local-brand-unisex-backpack-tl002',
                'image' => 'pk-sp7.webp',
                'price' => 299000,
                'sale_price' => NULL,
                'quantity' => 28,
                'description' => NULL,
                'rating' => 0.0,
                'category_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}